
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Saharach Kampliw  ## put your name
title: Computer Science  ## your title
location:  Ubon Ratchathani


## Social Profiles
https://www.facebook.com/saharach.kampliw.7  ## you dribbble account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
